### ISSUE TITLE
Building Azeroth map for 1.12 SEGFAULTs (nullptr dereference)

### ISSUE THREAD

**Issue by gtker** [namreeb/namigator#58]
Building the `Azeroth` map for 1.12 segfaults when building the map at around 60 percent. This happens even on `threads == 1`.

Seems to happen during `MHDR` at ADT `x=30`, `y=45` (more info in the backtrace below).

`gdb` backtrace:
```
0x000055555560a7ca in std::__shared_ptr<std::vector<unsigned char, std::allocator<unsigned char> >, (__gnu_cxx::_Lock_policy)2>::operator bool (this=0x0) at /usr/include/c++/11/bits/shared_ptr_base.h:1300
1300          { return _M_ptr != nullptr; }
(gdb) bt
#0  0x000055555560a7ca in std::__shared_ptr<std::vector<unsigned char, std::allocator<unsigned char> >, (__gnu_cxx::_Lock_policy)2>::operator bool (this=0x0)
    at /usr/include/c++/11/bits/shared_ptr_base.h:1300
#1  0x000055555560a74a in utility::BinaryStream::buffer (this=0x0)
    at ./utility/../utility/BinaryStream.hpp:34
#2  0x0000555555609e53 in utility::BinaryStream::GetChunkLocation (this=0x0, chunkName="MHDR",
    startLoc=0, result=@0x7fffa33fb888: 1)
    at ./utility/BinaryStream.cpp:156
#3  0x0000555555609e20 in utility::BinaryStream::GetChunkLocation (this=0x0, chunkName="MHDR",
    result=@0x7fffa33fb888: 1)
    at ./utility/BinaryStream.cpp:146
#4  0x000055555559ee3d in parser::Adt::Adt (this=0x7fff9910f130, map=0x55555597c500, adtX=30, adtY=45)
    at ./parser/Adt/Adt.cpp:75
#5  0x00005555555d4d4b in std::make_unique<parser::Adt, parser::Map*, int&, int&> ()
    at /usr/include/c++/11/bits/unique_ptr.h:962
#6  0x00005555555d3123 in parser::Map::GetAdt (this=0x55555597c500, x=30, y=45)
    at ./parser/Map/Map.cpp:231
#7  0x000055555558594f in MeshBuilder::BuildAndSerializeMapTile (this=0x555555a07760, tileX=479,
    tileY=719) at ./MapBuilder/MeshBuilder.cpp:926
#8  0x000055555559c434 in Worker::Work (this=0x55555597ac10)
    at ./MapBuilder/Worker.cpp:57
#9  0x000055555559cedc in std::__invoke_impl<void, void (Worker::*)(), Worker*> (
    __f=@0x55555597ac90: (void (Worker::*)(Worker * const)) 0x55555559c174 <Worker::Work()>,
    __t=@0x55555597ac88: 0x55555597ac10) at /usr/include/c++/11/bits/invoke.h:74
#10 0x000055555559ce2f in std::__invoke<void (Worker::*)(), Worker*> (
    __fn=@0x55555597ac90: (void (Worker::*)(Worker * const)) 0x55555559c174 <Worker::Work()>)
    at /usr/include/c++/11/bits/invoke.h:96
#11 0x000055555559cd8f in std::thread::_Invoker<std::tuple<void (Worker::*)(), Worker*> >::_M_invoke<0ul, 1ul> (this=0x55555597ac88) at /usr/include/c++/11/bits/std_thread.h:253
#12 0x000055555559cd44 in std::thread::_Invoker<std::tuple<void (Worker::*)(), Worker*> >::operator() (
    this=0x55555597ac88) at /usr/include/c++/11/bits/std_thread.h:260
#13 0x000055555559cd24 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (Worker::*)(), Worker*> > >::_M_run (this=0x55555597ac80) at /usr/include/c++/11/bits/std_thread.h:211
#14 0x00007ffff7cdc2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#15 0x00007ffff7894b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#16 0x00007ffff7926a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

SHA256sums of files:
```
0bb2d6d370d825353eff5d9282c545a1b61980baaa5b7b65b1a7521e0ee8e27a  backup.MPQ
f648e4fae190abcb25749ddbe96454e7e0de7e9c7e955983ed9d0e73b6986009  base.MPQ
d9d5a290bdad848e177e2731c7ef221a1d7a6793e2c94e431488dd40816101e2  dbc.MPQ
511189160f091eeb9d7ee8c473c1422b7f1fadbd9b65bfbf7d0a2a344103312d  fonts.MPQ
6545dfbb3ef21a8b7f36b577419494cc292fec35585f9a1511d6c8b692b83191  interface.MPQ
13aee674db39fc605c8aabf964eda0bb7895c6f026fed6c508bf2f9d155db0f9  misc.MPQ
a7aa78c234bbdd450e00434e5939aa1a02383df1971cddcbfa181d68e9ab45a2  model.MPQ
84f506c9f049f1e35f6d0f7b2e6643d28856888680ae2593436be8b9a058aad6  patch-2.MPQ
a9ad25c9a32600dd3c71f97a0f95f9b9b629a9995988b928975c8871f1197683  patch.MPQ
6ba131da952aae8d1e061b54468fd6e5d2ef78616540e2746ed21255d6b959a7  sound.MPQ
a1564120452cd75c4c7b2002a668b12250a35dab658816a33b591ebb23004f52  speech.MPQ
68fda6fb4f57051a47a0a56ff1757d73ee5c2a870774ba60ee8b52d7b36bc61d  terrain.MPQ
7e5996d2a0a2de03c79dcf9ab78f3fce66264688eee56ca6dbc51c8ce4433dac  texture.MPQ
9933d9ca23d481647880c9798dc7c225cd926f51026d148f09cd5251fc56edb7  wmo.MPQ
```

**Comment by namreeb** [comment]
Should be fixed with https://github.com/namreeb/namigator/commit/0d9dabfe31e8fb0ca4f17e4c08303a8dba3977ea.
